[project]
name = 'Decentralized-Rainwater-Harvesting-Coordination'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.quality-testing]
path = 'contracts/quality-testing.clar'
clarity_version = 2
epoch = 2.5

[contracts.system-registration]
path = 'contracts/system-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.volume-tracking]
path = 'contracts/volume-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
